version: '2'
services:
    web:
        build:
            context: ./web
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Paris"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: 'username'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'dbname'
volumes:
    mariadb:
